plugins {
    id 'java'
    id 'application'
    id 'jacoco'
}

group = 'rs.medikarton'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.46.1.3'
    implementation 'org.slf4j:slf4j-simple:2.0.13'

    testImplementation platform('org.junit:junit-bom:5.11.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'rs.medikarton.Main'
}

tasks.named('test') {
    useJUnitPlatform()
    // POKRECE 20 PROJEKTNIH TESTOVA
    filter {
        includeTestsMatching 'rs.medikarton.SazetiProjektniTest'
    }
    testLogging {
        events 'passed', 'skipped', 'failed'
        showStandardStreams = false
    }
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
        csv.required = true
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    'rs/medikarton/Main.class',
                    'rs/medikarton/Main$*.class'
            ])
        }))
    }
}

// PROVERA POKRIVENOSTI
tasks.named('check') {
    dependsOn jacocoTestCoverageVerification
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport
    violationRules {
        rule {
            limit {
                counter = 'INSTRUCTION'
                minimum = 0.80
            }
        }
        rule {
            limit {
                counter = 'BRANCH'
                minimum = 0.75
            }
        }
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    'rs/medikarton/Main.class',
                    'rs/medikarton/Main$*.class'
            ])
        }))
    }
}

tasks.named('run') {
    standardInput = System.in
}
